### ISSUE TITLE
Improved instructions for Debian

### ISSUE THREAD

**Issue by whitequark** [SEL4PROJ/sel4-tutorials#1]
The provided quick start instructions do not quite work on Debian. Notably:
- Debian doesn't have the `universe` repository. It has `contrib` instead.
- It's necessary to specify the distro version explicitly when adding a PPA, that is: `add-apt-repository 'deb http://ppa.launchpad.net/hvr/ghc/ubuntu trusty main'`.
- Debian does not provide `gcc-arm-linux-gnueabi` (it does provide `gcc-arm-none-eabi`). You'd need to figure some other way (I already had it installed locally so I wouldn't know which.)
- Debian does not provide `phablet-tools` but it appears that the only thing needed from there is `repo`, which it does provide.

I have built and ran both ARM and x86 versions.

**Comment by pingerino** [comment]
Thanks. More detailed instructions for setting up your system are provided on the developers wiki: https://wiki.sel4.systems/Getting%20started#Setting_up_your_machine

Please feel free to improve the docs for debian there :).
