### ISSUE TITLE
hello-4 recommends using badged cap for receiving

### ISSUE THREAD

**Issue by agacek** [SEL4PROJ/sel4-tutorials#14]
The hello-4 example recommends that the receiver use the badged cap for receiving. I would expect it to recommend just using the original (unbadged) cap.

https://github.com/SEL4PROJ/sel4-tutorials/blob/master/apps/hello-4/src/main.c#L238

https://github.com/SEL4PROJ/sel4-tutorials/blob/master/apps/hello-4/src/main.c#L272

**Comment by pingerino** [comment]
I've fixed this today, you should see the change come out soon. Thanks!
