### ISSUE TITLE
Outdated installation instructions

### ISSUE THREAD

**Issue by pjr2442** [SEL4PROJ/sel4-tutorials#18]
It appears as though the bash commands for git repo init and sync are outdated, and reference old repositories that no longer exist/no longer host the correct manifest and xml files. The tutorial page on the seL4 wiki has the correct instructions (or rather instructions that worked on my machine), which can be found here: https://wiki.sel4.systems/Tutorials

**Comment by pingerino** [comment]
Thanks, I've updated the README with the correct links and also added a link to the wiki.
