### ISSUE TITLE
Error During seL4 Tutorial Build

### ISSUE THREAD

**Issue by johnkrainski** [SEL4PROJ/sel4-tutorials#2]
I am receiving an error during the the x86 make tutorial.  I have executed all the steps on this page: 
https://github.com/seL4-projects/sel4-tutorials/blob/master/Prerequisites.md
Everything works including make ia32_simple_defconfig; make silentoldconfig.  When I execute the final make, lots of build activity occurs, then the make stops with the following error: "make: *** No rule to make target 'libsel4camkes', needed by 'libsel4muslccamkes'.  Stop."

I have a co-worker who has built this example before, and they tried with the latest repository and receive the same error.

Please advise.  Thank you,
John

**Comment by ikuz** [comment]
It seems like the behaviour of the 'repo' tool had changed, breaking some of our manifests.  I've fixed them, so if you try again, it should work.

**Comment by johnkrainski** [comment]
Your fixed worked.  Thanks. -John

**Comment by johnkrainski** [comment]
Thanks, Ihor.

John
