### ISSUE TITLE
When the CAmkES tutorials can be supported.

### ISSUE THREAD

**Issue by aogrcs** [SEL4PROJ/sel4-tutorials#23]
Hi, now it only support the native seL4 tutorials, when we can try the CAmkES tutorials? Thanks!
Sincerely!

**Comment by kent-mcleod** [comment]
Hi,
We should be releasing an updated version of the tutorials for CAmkES and native that use the new CMake build system soon (within the next couple of days).

**Comment by aogrcs** [comment]
Thanks, hope for it!
Sincerely!
