### ISSUE TITLE
Caught cap fault in send phase at address 0x0 while trying to handle:

### ISSUE THREAD

**Issue by j824737450** [SEL4PROJ/sel4-tutorials#24]
Hi,
I configure my environment according to https://docs.sel4.systems/HostDependencies, and I get the code following "repo init -u https://github.com/SEL4PROJ/sel4-tutorials-manifest -b refs/tags/sel4-tutorials-9.0.1
repo sync".  After "make pc99_hello-1_defcongfig" and "make", I run it by "qemu-system-i386 -nographic -m 512 -kernel images/kernel-ia32-pc99 -initrd images/hello-1-image-ia32-pc99". It successfully print "hello world". But when I do hello-2 like this, there is an exception :
"Caught cap fault in send phase at address 0x0
while trying to handle:
user exception 0x6 code 0x0
in thread 0xffaf7400 "rootserver" at address 0x80571eb
With stack:
0x807b2b0: 0x0
0x807b2b4: 0x0
0x807b2b8: 0x0
0x807b2bc: 0x0
0x807b2c0: 0x0
0x807b2c4: 0x0
0x807b2c8: 0x0
0x807b2cc: 0x0
0x807b2d0: 0x0
0x807b2d4: 0x0
0x807b2d8: 0x0
0x807b2dc: 0x0
0x807b2e0: 0x0
0x807b2e4: 0x0
0x807b2e8: 0x0
0x807b2ec: 0x0
"
I don't know what's wrong, and do you have any ideas? Thank you!

**Comment by kent-mcleod** [comment]
I believe you need to do at least Task 1 (https://docs.sel4.systems/Tutorials/seL4_Tutorial_2#task-1) which removes the crash.

**Comment by j824737450** [comment]
Thanks for your reply!  I did as following after fixing TASK1 as solutions:
one compilation :
mkdir build_hello_2
cd build_hello_2
../init-build.sh -DTUTORIAL=hello-2 -DTUT_BOARD=pc -DTUT_ARCH=x86
ninja
run it in qemu:
qemu-system-i386 -nographic -m 512 -kernel images/kernel-ia32-pc99 -initrd images/sel4_tutorial_executable-image-ia32-pc99
*******************************************************The printed logs :(skipping a part)
.......
 ELF-loading userland images from boot modules:
size=0x123000 v_entry=0x8048d91 v_start=0x8048000 v_end=0x816b000 p_start=0x170000 p_end=0x293000
Moving loaded userland images to final location: from=0x170000 to=0x136000 size=0x123000
Starting node #0 with APIC ID 0
XSAVE not supported
seL4 called fail at /home/jdx/jdx/0608sel4/seL4-tutorials/kernel/src/arch/x86/kernel/boot_sys.c:785 in function boot_sys, saying "boot_sys failed for some reason :(
"
halting...
Kernel entry via Interrupt, irq 0
*****************************************************************
the other compilation: in the tutorials folder
make pc99_hello-2_defcongfig  
make
qemu-system-i386 -nographic -m 512 -kernel images/kernel-ia32-pc99 -initrd images/hello-1-image-ia32-pc99
and that is the question I mentioned above. I just touched on seL4, so I don't know where I made a mistake. 
Thank you !
