### ISSUE TITLE
Small prototype issue with hello_2 tutorial in Task 9

### ISSUE THREAD

**Issue by gmottram** [SEL4PROJ/sel4-tutorials#25]
Hi,

The tutorials are really helpful, thank you.

In the hello_2 tutorial at Task 9, the  function prototype in the comments for seL4_TCB_Configure() contains a "seL4_Uint8 priority" argument which is also mentioned in Hint 5. Neither the solution nor the seL4 reference manual seem to agree that there is such a parameter.

Best,
Geoff

**Comment by kent-mcleod** [comment]
Correct, that parameter used to exist, but a new invocation `seL4_TCB_SetPriority` was created. I believe there is a call to this function right under the seL4_TCB_Configure().
I updated the comment in hello_2 to have the correct prototype.  Thanks for reporting this!
