### ISSUE TITLE
Shared Folder Warning during VirtualBox Startup

### ISSUE THREAD

**Issue by johnkrainski** [SEL4PROJ/sel4-tutorials#3]
Note: This is only a warning and doesn't seem to prevent the tutorials from working correctly, at least that I've found so far.

When I start VirtualBox with your provided virtual machine image (Version 4.3.18 -- I know 5.0.0 is recommended, but I cannot get that through my corporate repository yet), I get the following warning:

"The virtual machine execution may run into an error condition as described below.  We suggest that you take an appropriate action to avert the error.The shared folder 'Shared' could not be set up: Shared folder path '/Users/ikuz/VirtualBox VMs/Shared' is not absolute. The shared folder setup will not be complete.  It is recommended to power down the virtual machine and fix the shared folder settings while the machine is not running.  
Error ID: BrokenSharedFolder
Severity: Warning"

**Comment by ikuz** [comment]
This shouldn't happen with the new virtual box image.
