### ISSUE TITLE
dynamic-2 is misrendered on sel4.systems

### ISSUE THREAD

**Issue by maybe-sybr** [SEL4PROJ/sel4-tutorials#39]
- https://docs.sel4.systems/Tutorials/dynamic-2.html

It looks like the renderer has gotten confused about where code block fences start and end. It seems like it could be the fault of line 232 which has a closing fence with a leading space, but if not that then I have no idea.

**Comment by maybe-sybr** [comment]
Actually, scratch the thing about L232. It looks like it's the fault of the script which filters the appropriate chunks of the source markdown file. It removes a necessary newline between the starting code fence on L86 (in the source file) and the following line which is meant to be in the code block.

~~~
## Exercises

When you first run this tutorial, you will see a fault as follows:
```
/*--filter TaskCompletion("task-1", TaskContentType.ALL)--*/
Booting all finished, dropped to user space
Caught cap fault in send phase at address (nil)
while trying to handle:
/*-- endfilter -*/
~~~

My working tree of that exercise looks like:

~~~
## Exercises

When you first run this tutorial, you will see a fault as follows:
```Booting all finished, dropped to user space
Caught cap fault in send phase at address (nil)
while trying to handle:
~~~

**Comment by kent-mcleod** [comment]
Thanks for pointing this out.  I believe the cause is the extra '-' at the start of the first statement in each code block which eats the preceding newline char.  I'll try put up a fix
