### ISSUE TITLE
Mistake in capabilities tutorial

### ISSUE THREAD

**Issue by lainy** [SEL4PROJ/sel4-tutorials#47]
Not sure if this is the correct place to post this.

Lines 162-163 of [capabilities.md](https://github.com/SEL4PROJ/sel4-tutorials/blob/master/tutorials/capabilities/capabilities.md), which are lines 4-5 of the main.c file:
```c
size_t initial_cnode_object_size = BIT(info->initThreadCNodeSizeBits);
printf("Initial CNode is %zu bytes in size\n", initial_cnode_object_size);
```
However, `BIT(n)` is `1ul<<n`, so this is not in fact reporting the CNode size is bytes.

If I understand correctly, `BIT(info->initThreadCNodeSizeBits)` would be the number of `CSlots` the `CNode` can hold, so the `printf` should perhaps read:
```c
printf("Initial CNode is %zu slots in size\n", initial_cnode_object_size);
```

Of course this is inconsequential to what the tutorial is teaching, but it seemed worth pointing out.

**Comment by xurtis** [comment]
That does seem to be correct. If you want to make a quick PR to fix, we should be able to merge it fairly quickly.

**Comment by lainy** [comment]
Closing this, see comments on PR #48
