### ISSUE TITLE
Tutorial VM S3 link down

### ISSUE THREAD

**Issue by diekmann** [SEL4PROJ/sel4-tutorials#6]
In sel4-tutorials/README.md, the S3 link to the VirtualBox virtual machine appliance is down.

https://s3-us-west-1.amazonaws.com/sel4-developer-day/sel4-tutorial-lubuntu-15.04-v4.ova
<Code>NoSuchBucket</Code>

**Comment by ikuz** [comment]
We've removed that S3 file, so have removed the link from the README.
