### ISSUE TITLE
apps/hello-3 some confusing steps

### ISSUE THREAD

**Issue by ratmice** [SEL4PROJ/sel4-tutorials#7]
/\* TODO 12: make sure it is what we expected */
Already has the code in place.

/\* TODO 7: make a badged copy of it in our cspace. This copy will be used to send
     \* an IPC message to the original cap */
The TODO is described using vka_mint_object however the Error text below it mentions seL4_Mint 

The manual it links to describes seL4_CNode_Mint, I did not see a seL4_Mint described.
perhaps a link to the header where cspacepath_t is declared?

**Comment by pingerino** [comment]
Thanks for this. I just consulted the source, these comments have been addressed in the source. If it doesn't solve the issue for you, please open a new one referring to the latest souce.
